from resource_api.listeler.urunKartMenuList import UrunKartMenuList
from resource_api.listeler.urunBirimList import UrunBirimList
from resource_api.listeler.tedarikciSiparisList import TedarikciSiparisList
from resource_api.listeler.musteriList import MusteriList,UlkeyeGoreMusteriListApi,UlkeyeGoreMusteriListAyrintiApi
from resource_api.listeler.kullaniciList import*
from resource_api.listeler.ocakList import *

