from resource_api.yeniTeklifler.teklif import *
from resource_api.yeniTeklifler.teklifIslem import *
from resource_api.yeniTeklifler.musteriTeklif import MusteriListApi,MusteriDetaApi,MusteriTeklifIslemApi,MusteriYeniModel