from models.teklifler.ebat import EbatModel,EbatSchema
from models.teklifler.kategori import KategoriModel,KategoriSchema
from models.teklifler.musteri import MusteriModel,MusteriSchema
from models.teklifler.teklifler import TekliflerModel,TekliflerSchema
from models.teklifler.ulke import UlkeModel,UlkeSchema
from models.teklifler.urun import UrunModel,UrunSchema
from models.teklifler.urunKayit import UrunKayitModel,UrunKayitSchema
from models.teklifler.yapilacakIsler import YapilacakIslerModel,YapilacakIslerSchema
from models.teklifler.yuzeyIslem import YuzeyIslemModel,YuzeyIslemSchema
from models.temsilciSatislari.temsilciSatislari import *
from models.teklifler.bgpProjectsModel import *
