from marshmallow import fields,Schema


class TeklifSchema(Schema):
    id = fields.Int()
    tarih = fields.String()
    hatirlatmaTarihi = fields.String()
    hatirlatmaSonTarih = fields.String()
    musteriId = fields.Int()
    aciklama = fields.String()
    cfr = fields.Boolean()
    fob = fields.Boolean()
    dtp = fields.Boolean()
    fca = fields.Boolean()
    kullaniciId = fields.Int()
    goruldu = fields.Boolean()
    takipEt = fields.Boolean()
    kaynakYeri = fields.String()
    teklifYeri = fields.String()
    saritasNot = fields.String()
    hatirlatmaAciklama = fields.String()
    hatirlatmaId = fields.Int()
    satis = fields.Boolean()
    numuneGirisTarihi = fields.String()
    numuneHatirlatmaTarihi = fields.String()
    numuneHatirlatmaSonTarih = fields.String()
    numuneTrackingNo = fields.String()
    numuneOdenenTutar = fields.Float()
    numuneAlinanTutar = fields.Float()
    proformaPoNo= fields.String()
    proformaTarih = fields.String()
    proformaTutar = fields.Float()
    teklifCloud = fields.Boolean()
    proformaCloud = fields.Boolean()
    proformaCloudDosya = fields.String()
    numuneCloud = fields.Boolean()
    numuneCloudDosya = fields.String()
    sonGorulmeCloud = fields.Boolean()
    sonGorulmeCloudDosya = fields.String()
    teklifOncelik = fields.String()
    teklifCloudDosya = fields.String()
    proformaNot = fields.String()
    numuneNot = fields.String()
    sira = fields.Int()
    blist = fields.Boolean()
    company = fields.String()
    email = fields.String()
    phone = fields.String()

class TeklifModel:
    id = None
    tarih = ""
    hatirlatmaTarihi = ""
    hatirlatmaSonTarih = ""
    musteriId = None
    aciklama = ""
    cfr = False
    fob = False
    dtp = False
    fca = False
    kullaniciId = None
    goruldu = False
    takipEt = False
    kaynakYeri = ""
    teklifYeri = ""
    saritasNot = ""
    hatirlatmaAciklama = ""
    hatirlatmaId = None
    satis = False
    numuneGirisTarihi = ""
    numuneHatirlatmaTarihi = ""
    numuneHatirlatmaSonTarih = ""
    numuneTrackingNo = ""
    numuneOdenenTutar = 0
    numuneAlinanTutar = 0
    proformaPoNo= ""
    proformaTarih = ""
    proformaTutar = 0
    teklifCloud = False
    teklifCloudDosya = ""
    sonGorulmeCloud = False
    sonGorulmeCloudDosya =""
    proformaCloud = False
    proformaCloudDosya = ""
    numuneCloud = False
    numuneCloudDosya = ""
    teklifOncelik = ""
    proformaNot = ""
    numuneNot = ""
    sira = 0
    blist = False
    company = ""
    email = ""
    phone = ""