from models.finans.finans_ana_sayfa import *
from models.finans.musteri_ayrinti import *
from models.finans.musteri_odeme import *
from models.finans.musteri_odeme_secim import *
from models.finans.tahsilat import *
from models.finans.depo_ana_liste import *
from models.finans.depo_ayrinti import *
from models.finans.pesinat_islem import *
from models.finans.vade_analiste import *
from models.finans.odemelerList import *
from models.finans.marketing import *
