from views.raporlar.siparis_masraflar import SiparisMasraf
from views.raporlar.siparis_ceki import SiparisCeki
from views.raporlar.siparisGiderTur import SiparisGiderTur
from views.raporlar.anaSayfaDegisiklik import AnaSayfaDegisiklik
from views.raporlar.temsilciSatislari import TemsilciSatislari
from views.raporlar.dashboard.dashboard import DashboardNew
from views.raporlar.ceyreklikRapor.ceyreklikRapor import CeyreklikRaporlar